/**
 * The four payloads `docs/content-policy.md` publishes, built by the code that builds the real one.
 *
 * A documented payload that has drifted from the code is worse than no example, because it is a
 * promise about where somebody's mail goes. So the document does not describe these payloads: it
 * carries the output of this module, `npm run docs:examples` writes it there, and
 * `test/docs/content-policy-examples.test.ts` fails when the file and this module disagree. The same
 * goes for the block of privacy defaults above them. Each generated region is fenced off with markers,
 * so everything around them is still written by hand.
 *
 * Spec 09, criterion 15.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { fileConfigSchema } from '../../src/config/schema.js'
import { contentLevels, type ContentLevel } from '../../src/domain/content.js'
import {
  buildClassificationPayload,
  classificationRequestText,
  type ClassificationItem,
} from '../../src/llm/prompts/classification.js'

const DOCUMENT = 'docs/content-policy.md'

/**
 * Where each generated region starts and ends. The prose outside them is nobody's output.
 *
 * Three regions, because each of them was a second copy of something the code already says. The
 * payload blocks read `snippetChars` out of the schema while the settings block above them spelled the
 * same default out by hand, outside the markers and outside the test, so lowering the schema's default
 * left the document saying 300 in one place and 250 ten lines below it with the suite green. The table
 * of levels was hand-written in the same way, in an order nothing checked, while the notes under the
 * blocks chain off it ("The above, plus ..."): reordering `contentLevels` put `snippet` after `full` in
 * the table, the blocks the other way round, and `full`'s note under a `metadata` payload, with the
 * whole suite passing. All three are generated now.
 */
const LEVELS_BEGIN =
  '<!-- the levels, generated by tools/docs/content-policy-examples.ts: npm run docs:examples -->'
const LEVELS_END = '<!-- end of the generated levels -->'
const DEFAULTS_BEGIN =
  '<!-- the defaults, generated by tools/docs/content-policy-examples.ts: npm run docs:examples -->'
const DEFAULTS_END = '<!-- end of the generated defaults -->'
const EXAMPLES_BEGIN =
  '<!-- the payloads, generated by tools/docs/content-policy-examples.ts: npm run docs:examples -->'
const EXAMPLES_END = '<!-- end of the generated payloads -->'

/**
 * One inbox item, invented, and the only thing here that is not the real code's doing.
 *
 * Fixed rather than read from a database: these blocks are committed, so a payload built from a
 * clock or from whatever a machine happens to have captured would produce a diff nobody made.
 *
 * It carries no address, and that is the site refusing to publish anything shaped like one rather
 * than a claim that a real payload has no addresses in it: a real Gmail thread's `from` and
 * `participants` are addresses, and they go at `metadata` and above exactly as this name does. The
 * document says so beside the blocks.
 */
const item: ClassificationItem = {
  taskId: 'e2a1c7d4-0f3b-4a29-9c15-8b6d5e2f7a10',
  title: 'Re: Q3 capacity numbers for the board pack',
  provider: 'gmail',
  metadata: {
    from: 'Dana Whitfield (Finance)',
    participants: ['Dana Whitfield (Finance)', 'Ravi Patel (Operations)'],
    labels: ['INBOX', 'IMPORTANT'],
    messageCount: 4,
  },
  content:
    'Thanks for Tuesday. Before the board pack goes out on Friday we need the Q3 capacity numbers ' +
    'for the platform team: headcount at the end of each month, days lost to onboarding, and the ' +
    'split between client work and internal work. Ravi has the payroll export if that is easier ' +
    'than counting it again, and last quarter the finance team rounded to whole days, so please ' +
    'do the same for comparability. If the split is going to take a while, send the headcount ' +
    'first and we will follow up on the rest afterwards.',
  createdAt: Date.parse('2026-08-10T08:12:00Z'),
}

/** The moment the call is made, so `ageDays` is arithmetic on two fixed instants. */
const CALLED_AT = Date.parse('2026-08-12T09:00:00Z')

/**
 * The privacy settings a reader has not changed, read out of the schema rather than written again
 * here. They appear in the settings block, in each payload block's note and in the length of the
 * `snippet` payload, so a second copy of any of them is a number that can go quietly false: both
 * sides of a drift comparison would read the copy, and the test would stay green while several
 * statements in the document became untrue.
 */
const privacyDefaults = fileConfigSchema.parse({}).privacy
const SNIPPET_CHARS = privacyDefaults.snippetChars

/**
 * Which of the settings takes a trailing comment, and what it says. The two level fields are the ones
 * whose value is a choice out of a list, and the list is the domain's rather than a repetition of it,
 * so a level added to `contentLevels` shows up here without anybody editing the document.
 */
const settingComments: Readonly<Partial<Record<keyof typeof privacyDefaults, string>>> = {
  llmContent: contentLevels.join(' | '),
  storeContent: contentLevels.join(' | '),
}

/**
 * What each level includes, in a table cell. The vocabulary is the domain's, so a level added to
 * `contentLevels` does not compile until somebody says what it includes, and it cannot be added to the
 * page in one order and to the payloads below in another.
 *
 * `snippetChars` by name rather than by value: the number belongs to the schema, and the settings block
 * above is where the page quotes it.
 */
const includes: Readonly<Record<ContentLevel, string>> = {
  none: 'Nothing beyond internal ids. Classification cannot work at this level, and says so rather than guessing',
  metadata:
    "Sender, recipients, subject or title, timestamps, labels, pull-request stats, and the prose Caroline wrote about its own scheduling: a plan's summary and an entry's rationale. No body",
  snippet: 'Metadata plus the first `snippetChars` characters of the body',
  full: 'Metadata plus the whole body',
}

/** The table of levels: one row each, in the order the vocabulary declares them. */
export function levelsMarkdown(): string {
  const rows = contentLevels.map((level) => `| \`${level}\` | ${includes[level]} |`)

  return `${LEVELS_BEGIN}

| Level | What it includes |
| --- | --- |
${rows.join('\n')}

${LEVELS_END}`
}

/** The settings block: the defaults, as `caroline.config.json` would spell them. */
export function defaultsMarkdown(): string {
  const keys = Object.keys(privacyDefaults) as (keyof typeof privacyDefaults)[]
  const settings = keys.map((key, index) => ({
    text: `    ${JSON.stringify(key)}: ${JSON.stringify(privacyDefaults[key])}${index === keys.length - 1 ? '' : ','}`,
    comment: settingComments[key],
  }))

  // The comments line up, so the column is a column. Two spaces clear of the longest commented line.
  const width =
    Math.max(...settings.filter((setting) => setting.comment !== undefined).map(({ text }) => text.length)) + 2
  const lines = settings.map(({ text, comment }) =>
    comment === undefined ? text : `${text.padEnd(width)}// ${comment}`,
  )

  return `${DEFAULTS_BEGIN}

\`\`\`jsonc
{
  "privacy": {
${lines.join('\n')}
  }
}
\`\`\`

${DEFAULTS_END}`
}

/**
 * The user turn of a classification call at each level, as the provider receives it: the payload
 * assembled by `buildClassificationPayload` and rendered by `classificationRequestText`, which are
 * the two functions the classify job itself calls.
 */
export function payloadExamples(): readonly { readonly level: ContentLevel; readonly sent: string }[] {
  return contentLevels.map((level) => ({
    level,
    sent: classificationRequestText(
      buildClassificationPayload(item, { llmContent: level, snippetChars: SNIPPET_CHARS }, CALLED_AT),
    ),
  }))
}

/** What each level's block says about itself, above the payload rather than inside it. */
const notes: Readonly<Record<ContentLevel, string>> = {
  none: 'Nothing but the ids. The classifier does not call at this level, because there is nothing to sort on, and the boundary holds even if something did.',
  metadata:
    'The subject, who is on the thread, its labels, how many messages it has, and how old it is. No body.',
  snippet: `The above, plus the first ${SNIPPET_CHARS} characters of the body. This is the default. The body is cut at ${SNIPPET_CHARS} characters and not at the nearest word, because the cap is a disclosure limit rather than a display one.`,
  full: 'The above, with the body whole. Refuses to start against Anthropic or OpenAI unless `allowFullContentToRemoteProvider` is set as well.',
}

/** The generated region, markers included: what the document holds between them, exactly. */
export function examplesMarkdown(): string {
  const blocks = payloadExamples().map(
    ({ level, sent }) => `### \`${level}\`

${notes[level]}

\`\`\`text
${sent}
\`\`\``,
  )

  return `${EXAMPLES_BEGIN}\n\n${blocks.join('\n\n')}\n\n${EXAMPLES_END}`
}

/**
 * A region of the document this module owns: the markers that fence it off, and what belongs between
 * them. The test walks this list, so a region added here is checked for drift without being named
 * twice.
 */
export interface GeneratedRegion {
  /** What it is, for the failure message. */
  readonly name: string
  readonly begin: string
  readonly end: string
  /** The region as it should read, markers included. */
  readonly markdown: () => string
}

export const regions: readonly GeneratedRegion[] = [
  {
    name: 'the privacy defaults',
    begin: DEFAULTS_BEGIN,
    end: DEFAULTS_END,
    markdown: defaultsMarkdown,
  },
  { name: 'the table of levels', begin: LEVELS_BEGIN, end: LEVELS_END, markdown: levelsMarkdown },
  { name: 'the payloads', begin: EXAMPLES_BEGIN, end: EXAMPLES_END, markdown: examplesMarkdown },
]

/** Where a region sits in the document, or the complaint that it does not. */
function bounds(
  markdown: string,
  region: GeneratedRegion,
): { readonly start: number; readonly end: number } {
  const start = markdown.indexOf(region.begin)
  const end = markdown.indexOf(region.end)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `${DOCUMENT} has no generated region for ${region.name}: it needs the ${region.begin} and ${region.end} markers, in that order`,
    )
  }

  return { start, end: end + region.end.length }
}

/** The region as the document holds it, for the test that the two agree. */
export function regionOf(markdown: string, region: GeneratedRegion): string {
  const { start, end } = bounds(markdown, region)

  return markdown.slice(start, end)
}

/** The document with every generated region replaced. Everything outside the markers is untouched. */
export function documentWith(markdown: string): string {
  return regions.reduce((document, region) => {
    const { start, end } = bounds(document, region)

    return `${document.slice(0, start)}${region.markdown()}${document.slice(end)}`
  }, markdown)
}

// Run as a script rather than imported: rewrite the document. The test imports this module and only
// compares, so the rewrite is behind the entry-point check.
if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const markdown = readFileSync(DOCUMENT, 'utf8')
  const next = documentWith(markdown)
  writeFileSync(DOCUMENT, next, 'utf8')
  process.stdout.write(
    next === markdown
      ? `${DOCUMENT} was already up to date\n`
      : `Rewrote the generated regions in ${DOCUMENT}\n`,
  )
}
