/**
 * The four payloads `docs/content-policy.md` publishes, built by the code that builds the real one.
 *
 * A documented payload that has drifted from the code is worse than no example, because it is a
 * promise about where somebody's mail goes. So the document does not describe these payloads: it
 * carries the output of this module, `npm run docs:examples` writes it there, and
 * `test/docs/content-policy-examples.test.ts` fails when the file and this module disagree. The
 * generated region is fenced off with markers, so everything around it is still written by hand.
 *
 * Spec 09, criterion 14.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { contentLevels, type ContentLevel } from '../../src/domain/content.js'
import {
  buildClassificationPayload,
  classificationRequestText,
  type ClassificationItem,
} from '../../src/llm/prompts/classification.js'

/** Where the generated region starts and ends. The prose outside them is nobody's output. */
export const EXAMPLES_BEGIN =
  '<!-- generated by tools/docs/content-policy-examples.ts: npm run docs:examples -->'
export const EXAMPLES_END = '<!-- end of the generated payloads -->'

const DOCUMENT = 'docs/content-policy.md'

/**
 * One inbox item, invented, and the only thing here that is not the real code's doing.
 *
 * Fixed rather than read from a database: these blocks are committed, so a payload built from a
 * clock or from whatever a machine happens to have captured would produce a diff nobody made.
 *
 * It carries no address, and that is the site refusing to publish anything shaped like one rather
 * than a claim that a real payload has no addresses in it: a real Gmail thread's `from` and
 * `participants` are addresses, and they go at `metadata` and above exactly as this name does. The
 * document says so beside the blocks.
 */
const item: ClassificationItem = {
  taskId: 'e2a1c7d4-0f3b-4a29-9c15-8b6d5e2f7a10',
  title: 'Re: Q3 capacity numbers for the board pack',
  provider: 'gmail',
  metadata: {
    from: 'Dana Whitfield (Finance)',
    participants: ['Dana Whitfield (Finance)', 'Ravi Patel (Operations)'],
    labels: ['INBOX', 'IMPORTANT'],
    messageCount: 4,
  },
  content:
    'Thanks for Tuesday. Before the board pack goes out on Friday we need the Q3 capacity numbers ' +
    'for the platform team: headcount at the end of each month, days lost to onboarding, and the ' +
    'split between client work and internal work. Ravi has the payroll export if that is easier ' +
    'than counting it again, and last quarter the finance team rounded to whole days, so please ' +
    'do the same for comparability. If the split is going to take a while, send the headcount ' +
    'first and we will follow up on the rest afterwards.',
  createdAt: Date.parse('2026-08-10T08:12:00Z'),
}

/** The moment the call is made, so `ageDays` is arithmetic on two fixed instants. */
const CALLED_AT = Date.parse('2026-08-12T09:00:00Z')

/** The default, which is the number in the document's prose and the one a reader has not changed. */
const SNIPPET_CHARS = 300

/**
 * The user turn of a classification call at each level, as the provider receives it: the payload
 * assembled by `buildClassificationPayload` and rendered by `classificationRequestText`, which are
 * the two functions the classify job itself calls.
 */
export function payloadExamples(): readonly { readonly level: ContentLevel; readonly sent: string }[] {
  return contentLevels.map((level) => ({
    level,
    sent: classificationRequestText(
      buildClassificationPayload(item, { llmContent: level, snippetChars: SNIPPET_CHARS }, CALLED_AT),
    ),
  }))
}

/** What each level's block says about itself, above the payload rather than inside it. */
const notes: Readonly<Record<ContentLevel, string>> = {
  none: 'Nothing but the ids. The classifier does not call at this level, because there is nothing to sort on, and the boundary holds even if something did.',
  metadata:
    'The subject, who is on the thread, its labels, how many messages it has, and how old it is. No body.',
  snippet: `The above, plus the first ${SNIPPET_CHARS} characters of the body. This is the default. The body is cut at ${SNIPPET_CHARS} characters and not at the nearest word, because the cap is a disclosure limit rather than a display one.`,
  full: 'The above, with the body whole. Refuses to start against Anthropic or OpenAI unless `allowFullContentToRemoteProvider` is set as well.',
}

/** The generated region, markers included: what the document holds between them, exactly. */
export function examplesMarkdown(): string {
  const blocks = payloadExamples().map(
    ({ level, sent }) => `### \`${level}\`

${notes[level]}

\`\`\`text
${sent}
\`\`\``,
  )

  return `${EXAMPLES_BEGIN}\n\n${blocks.join('\n\n')}\n\n${EXAMPLES_END}`
}

/** Where the generated region sits in the document, or the complaint that it does not. */
function bounds(markdown: string): { readonly start: number; readonly end: number } {
  const start = markdown.indexOf(EXAMPLES_BEGIN)
  const end = markdown.indexOf(EXAMPLES_END)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `${DOCUMENT} has no generated region: it needs the ${EXAMPLES_BEGIN} and ${EXAMPLES_END} markers, in that order`,
    )
  }

  return { start, end: end + EXAMPLES_END.length }
}

/** The document with its generated region replaced. Everything outside the markers is untouched. */
export function documentWith(markdown: string, region: string): string {
  const { start, end } = bounds(markdown)

  return `${markdown.slice(0, start)}${region}${markdown.slice(end)}`
}

/** The region as the document holds it, for the test that the two agree. */
export function regionOf(markdown: string): string {
  const { start, end } = bounds(markdown)

  return markdown.slice(start, end)
}

// Run as a script rather than imported: rewrite the document. The test imports this module and only
// compares, so the rewrite is behind the entry-point check.
if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const markdown = readFileSync(DOCUMENT, 'utf8')
  const next = documentWith(markdown, examplesMarkdown())
  writeFileSync(DOCUMENT, next, 'utf8')
  process.stdout.write(
    next === markdown ? `${DOCUMENT} was already up to date\n` : `Rewrote the payloads in ${DOCUMENT}\n`,
  )
}
