/**
 * `.github/copilot-instructions.md`, written from `AGENTS.md`.
 *
 * `AGENTS.md` is the one authoritative copy of the conventions, and most of Copilot reads it where
 * it is: the coding agent on github.com, Copilot code review, the cloud agent in VS Code and the
 * other editors, and the Copilot CLI. Copilot Chat, on every platform, and Visual Studio do not.
 * They read `.github/copilot-instructions.md` and nothing else, which is the whole reason a second
 * file is worth having.
 *
 * That second file used to be a symlink, so a working tree saw the conventions and the GitHub API
 * saw a blob holding the twelve bytes `../AGENTS.md`. The surface most likely to be reading the path
 * was served a filename. It is a real file now, this module writes it with `npm run docs:copilot`,
 * and `test/docs/copilot-instructions.test.ts` fails when the two disagree, so the copy is checked
 * rather than remembered.
 */
import { lstatSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/** The authoritative conventions. Every word of the copy comes from here. */
export const SOURCE = 'AGENTS.md'

/** The copy, at the only path Copilot Chat and Visual Studio read. */
export const DOCUMENT = '.github/copilot-instructions.md'

/** What rewrites the copy, named in the failure message so it does not have to be looked up. */
export const COMMAND = 'npm run docs:copilot'

/**
 * The notice the copy opens with, and the only part of it that is not `AGENTS.md`.
 *
 * An HTML comment, so a reader of the rendered page is not told about the plumbing before the
 * conventions, while anybody editing the file is told at the first line. It says where the file came
 * from and what to edit instead, because a copy that looks hand-maintained gets hand-edited.
 *
 * It also says that the links below it are relative to the repository root: the body is `AGENTS.md`
 * byte for byte, so its links resolve from there and not from `.github`. Rewriting them would make
 * the copy something other than the source, and then the check that they are identical would be
 * checking a transformation instead of a copy.
 */
export const NOTICE = `<!--
Generated from ${SOURCE} by ${COMMAND}. Do not edit this file: edit ${SOURCE}, then run that command.
test/docs/copilot-instructions.test.ts fails when this copy and ${SOURCE} disagree.

${SOURCE} is the authoritative copy, and most of Copilot reads it there: the coding agent, Copilot
code review, the cloud agent in the editors, and the CLI. Copilot Chat and Visual Studio read only
this path, which is why the copy exists.

Links below are relative to the repository root, because this is ${SOURCE} verbatim.
-->`

/** Whether a path is a symlink, which is what the copy replaced and must not become again. */
function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink()
  } catch {
    return false
  }
}

/** The copy as it should read: the notice, a blank line, and the whole of the source. */
export function copilotInstructions(): string {
  return `${NOTICE}\n\n${readFileSync(SOURCE, 'utf8')}`
}

// Run as a script rather than imported: rewrite the copy. The test imports this module and only
// compares, so the rewrite is behind the entry-point check.
if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const next = copilotInstructions()
  const current = (() => {
    try {
      return readFileSync(DOCUMENT, 'utf8')
    } catch {
      return undefined
    }
  })()

  if (current === next && !isSymlink(DOCUMENT)) {
    process.stdout.write(`${DOCUMENT} was already up to date\n`)
  } else {
    // Removed first, because writing to a symlink writes through it: the copy this file replaced
    // pointed at the source, and a plain write would have rewritten the conventions themselves.
    if (isSymlink(DOCUMENT)) {
      rmSync(DOCUMENT)
    }
    writeFileSync(DOCUMENT, next, 'utf8')
    process.stdout.write(`Wrote ${DOCUMENT} from ${SOURCE}\n`)
  }
}
