/**
 * The public site. Spec 11.
 *
 * The site is a shell around documentation that already exists. Every page but the home page is a
 * Markdown file from the repository, rendered, with the links between those files rewritten to the
 * pages that render them. Nothing here writes prose, because a setup guide maintained in two places
 * is a setup guide that is wrong in one of them.
 *
 * Three things it does that a Markdown-to-HTML call does not:
 *
 * - **Rewrites the links.** The documents link to each other by file path, and a fragment such as
 *   `#6b-the-consent-screen` was written against GitHub's heading slugs. Both have to keep working
 *   somewhere those paths do not exist, and a link that resolves to nothing fails the build.
 * - **Borrows the application's palette.** The tokens are extracted from `web/styles.css` rather
 *   than copied, so there is one palette and not two that drift.
 * - **Returns its output instead of writing it.** `site/main.ts` writes the map to disk; the suite
 *   asserts against it in memory, which is how every page can be compared with its source without a
 *   temporary directory to clean up.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { join, posix } from 'node:path'
import { Marked, type Tokens } from 'marked'

/**
 * Where the repository's files come from. A parameter so the suite can build a broken tree, and the
 * whole of what the build reads: two calls, both of them at a path inside the repository, so the output
 * is a function of the tree and of nothing else about the machine.
 */
export interface SiteSources {
  read(repositoryPath: string): string
  list(repositoryPath: string): string[]
}

export interface SitePage {
  /** The Markdown file this page renders, relative to the repository root. */
  readonly source: string
  /** Where the page is written, relative to the site root. */
  readonly output: string
  /** The `<title>`, and what the page is called wherever it is named. */
  readonly title: string
}

export function repositorySources(root: string = process.cwd()): SiteSources {
  return {
    read: (repositoryPath) => readFileSync(join(root, repositoryPath), 'utf8'),
    list: (repositoryPath) => readdirSync(join(root, repositoryPath)).sort(),
  }
}

/**
 * The navigation, and the whole of it. Four entries: where you are, the one thing most readers came
 * for, what to do with it once it runs, and the contract behind them. `docs.html` is gone: its
 * "read it for" table said exactly what the docs shell's grouped sidebar now says, so pointing a
 * fifth nav entry at it would be one more place for that list to drift from the sidebar's. The
 * sidebar is a docs page's own navigation into everything the flat nav used to reach for it, and the
 * top nav stays identical on every page, which is criterion 10, unchanged by adding it.
 */
const navigation = [
  { label: 'Home', output: 'index.html' },
  { label: 'Setup', output: 'setup.html' },
  { label: 'Using it', output: 'using.html' },
  { label: 'Specs', output: 'specs/index.html' },
] as const

/**
 * The pages that are not specs. The specs are read from the directory instead, so a spec added
 * later is published by adding the spec.
 *
 * `docs/README.md` is no longer one of these: its "read it for" table is exactly what the docs
 * shell's grouped sidebar says once it exists, and a page whose entire content is a second copy of
 * the sidebar is the drift spec 11 exists to rule out. The file itself is untouched, for GitHub's
 * own file viewer; the site simply stops publishing it, and `reference.html` picks up the one link
 * to it the removed page used to carry, in the sidebar's Reference group.
 */
const fixedPages: readonly SitePage[] = [
  { source: 'site/pages/index.md', output: 'index.html', title: 'Caroline' },
  { source: 'docs/setup.md', output: 'setup.html', title: 'Setting Caroline up' },
  { source: 'docs/using.md', output: 'using.html', title: 'Using Caroline' },
  {
    source: 'docs/content-policy.md',
    output: 'content-policy.html',
    title: 'What leaves the machine',
  },
  { source: 'README.md', output: 'reference.html', title: 'Caroline in short' },
  { source: 'docs/plan.md', output: 'plan.html', title: 'Implementation plan' },
  { source: 'docs/specs/README.md', output: 'specs/index.html', title: 'Specs' },
]

/**
 * Where the documentation's images live, and the only directory the site publishes anything from that
 * is not a document. They are screenshots of the seeded demonstration day, generated by
 * `npm run demo:shoot -- --docs`, which is what keeps them true: a hand-captured picture of somebody's
 * own board would be both stale and a disclosure.
 */
const imageDirectory = 'docs/images'

/**
 * The images, as source path to output path. Copied rather than rendered, and copied by `site/main.ts`:
 * this module returns text, and a PNG through a string is a PNG with its bytes rewritten.
 */
export function siteAssets(
  sources: SiteSources = repositorySources(),
): readonly { readonly source: string; readonly output: string }[] {
  return sources
    .list(imageDirectory)
    .filter((name) => name.endsWith('.png'))
    .map((name) => ({ source: `${imageDirectory}/${name}`, output: `images/${name}` }))
}

function manifest(sources: SiteSources): readonly SitePage[] {
  const specs = sources
    .list('docs/specs')
    .filter((name) => /^\d\d-.*\.md$/.test(name))
    .map((name) => ({
      source: `docs/specs/${name}`,
      output: `specs/${name.replace(/\.md$/, '.html')}`,
      title: headingOf(sources.read(`docs/specs/${name}`)),
    }))

  return [...fixedPages, ...specs]
}

/**
 * The pages of a tree, which is what the suite asserts against. A function rather than a constant: as a
 * constant it read `docs/specs` when the module was imported, so importing it from anywhere but the
 * repository root threw before any caller could say where the tree was.
 */
export const sitePages = (sources: SiteSources = repositorySources()): readonly SitePage[] =>
  manifest(sources)

/**
 * The blocks of a document. Either line ending, because a Windows checkout with `core.autocrlf` set
 * separates paragraphs with `\r\n\r\n`, and splitting on `\n\n` there makes every file one block: the
 * home page loses the README's opening and every description becomes the whole document.
 */
const paragraphs = (markdown: string): string[] => markdown.split(/\r?\n\r?\n/)

/** The first `#` heading of a document: what the document calls itself. */
function headingOf(markdown: string): string {
  return (/^# (.+)$/m.exec(markdown)?.[1] ?? 'Caroline').trim()
}

/**
 * GitHub's heading slug, because the fragments in the documents were written against it: lowercased,
 * punctuation dropped, spaces hyphenated. `## 6b. The consent screen` is `#6b-the-consent-screen`
 * here exactly as it is there.
 */
export function slug(heading: string): string {
  // Trimmed before the punctuation goes, which is the order github-slugger uses: `## What now ?` is
  // `#what-now-` there, because the space the `?` leaves behind becomes a hyphen. Trimming afterwards
  // would drop it and refuse a fragment GitHub is right about.
  return heading
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N} _-]/gu, '')
    .replace(/\s/g, '-')
}

const escapeText = (value: string): string =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const escapeAttribute = (value: string): string => escapeText(value).replace(/"/g, '&quot;')

/**
 * A URL, escaped for an attribute. Only a bare `&` becomes `&amp;`: a document that writes a query
 * string as `?a=1&amp;b=2`, which is what somebody escaping by habit writes, would otherwise be
 * published as `&amp;amp;` and requested with the entity in it.
 *
 * All three spellings of an entity are exempt, not two: a name may carry digits (`&sup2;`) and a numeric
 * reference may be hexadecimal (`&#x27;`), and escaping either would be the thing this exists to avoid.
 */
const escapeUrl = (url: string): string =>
  url
    .replace(/&(?!(?:[a-z][a-z0-9]*|#\d+|#x[0-9a-f]+);)/gi, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

/**
 * Rendered inline HTML back to the text a reader sees. Headings are slugged from this rather than from
 * their Markdown, because GitHub slugs the rendered text: a heading written as `## See [the docs](x)`
 * is `#see-the-docs` there, and slugging the source would make it `see-the-docsx`. The entities come
 * back with the tags, or a heading containing an `&` would slug as `amp`.
 */
const readAsText = (html: string): string =>
  html
    .replace(/<[^>]*>/g, '')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
const isAbsolute = (href: string): boolean =>
  /^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith('//')

/**
 * The repository, from `package.json`, so the one place that already names it stays the only one. It
 * is where a link to a file the site does not publish goes, and where the footer sends a reader who
 * wants to correct a page.
 */
function repositoryUrl(sources: SiteSources): string {
  const url = String(JSON.parse(sources.read('package.json')).repository?.url ?? '')
  // The repository name may contain a dot. Only a trailing `.git` is a suffix, so it is anchored at
  // the end rather than excluded from the name, which truncated `caroline.dev` to `caroline`.
  const slugged = /github\.com[/:]([^/]+\/[^/]+?)(?:\.git)?$/.exec(url)?.[1]
  if (slugged === undefined) throw new Error('package.json names no GitHub repository to link to')

  return `https://github.com/${slugged}`
}

/**
 * The id the layout puts on `<main>`, for the skip link. A heading whose slug is this one is refused,
 * because the alternatives are both worse: numbering it `content-1` leaves a `#content` written against
 * GitHub matching the shell and scrolling the reader to the top of the page rather than to the section,
 * which is the guarantee criterion 3 makes, and letting it through puts the same id on the page twice.
 */
const contentIdentifier = 'content'

/**
 * One row of the setup guide's own step table: `| [1. What you need](#1-what-you-need) | Node 24 |
 * 2 minutes |`. Read from the source Markdown rather than written a second time here, so the docs
 * shell's sidebar and the landing page's "Running in an afternoon" cards cannot say a number the
 * table itself does not.
 */
export interface SetupStep {
  readonly number: number
  readonly label: string
  readonly anchor: string
  readonly get: string
  readonly roughly: string
}

const stepRow =
  /^\|\s*\[(\d+)\.\s*([^\]]+)\]\(#([^)]+)\)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*$/gm

/**
 * An empty result rather than a thrown one when the table is not there: a document overridden down
 * to a stub, to test something this table has nothing to do with, is not a broken build. The real
 * `docs/setup.md` always has the table, and `sidebarGroups` and `afternoonCards` both degrade to
 * showing nothing built from it rather than refusing the rest of the page over its absence.
 */
export function setupSteps(markdown: string): readonly SetupStep[] {
  return [...markdown.matchAll(stepRow)].map((match) => ({
    number: Number(match[1]),
    label: (match[2] ?? '').trim(),
    anchor: match[3] ?? '',
    get: (match[4] ?? '').trim(),
    roughly: (match[5] ?? '').trim(),
  }))
}

/** The leading integer of "2 minutes", "20 minutes": the number the table states, read rather than retyped. */
function minutesOf(roughly: string): number {
  const minutes = /^(\d+)/.exec(roughly)?.[1]
  if (minutes === undefined)
    throw new Error(`docs/setup.md states an estimate this build cannot read: "${roughly}"`)

  return Number(minutes)
}

/** "2 minutes" as the sidebar prints it: short, because eleven of them run down a column. */
const shortMinutes = (roughly: string): string => `${minutesOf(roughly)} min`

/**
 * The heading identifiers a document's Markdown would slug to, read directly from the source rather
 * than from a full render: the sidebar only wants to know whether a fragment it hardcodes actually
 * exists in `docs/setup.md` before linking to it, and a document overridden down to a stub for a test
 * about something else entirely should not fail the build over a sidebar entry that has nothing to
 * do with what the test is testing.
 */
function headingIdentifiers(markdown: string): ReadonlySet<string> {
  const identifiers = new Set<string>()
  let fenced = false
  for (const line of markdown.split('\n')) {
    if (line.startsWith('```')) fenced = !fenced
    else if (!fenced && /^#{1,6} /.test(line)) {
      identifiers.add(slug(line.replace(/^#{1,6} /, '').trim()))
    }
  }

  return identifiers
}

/**
 * The four cards of "Running in an afternoon, checked at every step": the setup guide's own numbers,
 * for the steps that state what a fresh install gets you rather than where a file lives. Steps 1 and
 * 2 are one card, because nothing runs until both are done, and the card states their combined time.
 */
export function afternoonCards(
  steps: readonly SetupStep[],
): readonly { readonly time: string; readonly title: string; readonly body: string }[] {
  const step = (number: number): SetupStep | undefined =>
    steps.find((candidate) => candidate.number === number)

  const first = step(1)
  const second = step(2)
  const model = step(4)
  const github = step(5)
  const google = step(6)
  // A stub of the table in a test that has nothing to do with these cards: the cards are simply
  // empty rather than the build refusing over a table that only matters to this landing section.
  if (
    first === undefined ||
    second === undefined ||
    model === undefined ||
    github === undefined ||
    google === undefined
  ) {
    return []
  }

  return [
    {
      time: `${minutesOf(first.roughly) + minutesOf(second.roughly)} min`,
      title: second.label,
      body: second.get,
    },
    { time: `+${minutesOf(model.roughly)} min`, title: model.label, body: model.get },
    { time: `+${minutesOf(github.roughly)} min`, title: github.label, body: github.get },
    { time: `+${minutesOf(google.roughly)} min`, title: google.label, body: google.get },
  ]
}

/**
 * The docs shell's grouped sidebar: what replaced the flat top nav's job of getting a reader from one
 * document to another. Four groups, each named the way the issue names it; "Set up in order" is the
 * setup guide's own step table, read live, and shown only while a setup page is open, because eleven
 * extra links are clutter on every other page.
 *
 * A link is either a page (source path, resolved through `context.outputs` exactly as `actions` and
 * `resolve` do) or a fragment on `setup.html` (a section the guide already has, given a sidebar entry
 * of its own rather than a new page). "What Caroline is" is the home page under the label a reader
 * looking for documentation would use for it.
 */
interface SidebarLink {
  readonly label: string
  readonly target: string
  readonly detail?: string
}
interface SidebarGroup {
  readonly heading: string
  readonly links: readonly SidebarLink[]
}

function sidebarGroups(
  context: BuildContext,
  steps: readonly SetupStep[],
): readonly SidebarGroup[] {
  const page = (source: string): string => {
    const output = context.outputs.get(source)
    if (output === undefined) throw new Error(`the sidebar cannot link to ${source}`)

    return output
  }
  const setup = page('docs/setup.md')
  // `docs/setup.md`'s own headings, read directly rather than assumed: a test that overrides the file
  // down to a stub, to test something else entirely, should not fail the build over a sidebar entry
  // pointing at a heading a stub does not have.
  const setupHeadings = headingIdentifiers(context.sources.read('docs/setup.md'))
  const onSetup = (anchor: string, label: string): readonly SidebarLink[] =>
    setupHeadings.has(anchor) ? [{ label, target: `${setup}#${anchor}` }] : []

  return [
    {
      heading: 'Start here',
      links: [
        { label: 'What Caroline is', target: page('site/pages/index.md') },
        { label: 'Setting it up', target: setup },
        { label: 'Using it day to day', target: page('docs/using.md') },
      ],
    },
    {
      heading: 'Set up, in order',
      links: steps.map((current) => ({
        label: `${current.number}. ${current.label}`,
        target: `${setup}#${current.anchor}`,
        detail: shortMinutes(current.roughly),
      })),
    },
    {
      heading: 'Trust',
      links: [
        { label: 'What leaves the machine', target: page('docs/content-policy.md') },
        ...onSetup('8-reaching-it-from-elsewhere', 'Logins and exposure'),
        ...onSetup('11-removing-everything', 'Removing everything'),
      ],
    },
    {
      heading: 'Reference',
      links: [
        { label: 'Specs 00–13', target: page('docs/specs/README.md') },
        ...onSetup('troubleshooting', 'Troubleshooting'),
        { label: 'Implementation plan', target: page('docs/plan.md') },
        { label: 'Caroline in short', target: page('README.md') },
      ],
    },
  ]
}

/**
 * The sidebar, rendered for a page: every group but "Set up, in order" is shown always, that one only
 * while the reader is on `setup.html` itself, where the eleven steps are what the page is about
 * rather than clutter borrowed from another page.
 */
function sidebar(page: SitePage, context: BuildContext, steps: readonly SetupStep[]): string {
  const href = (target: string) => posix.relative(posix.dirname(page.output), target)
  const groups = sidebarGroups(context, steps).filter(
    (group) =>
      group.heading !== 'Set up, in order' || page.output === context.outputs.get('docs/setup.md'),
  )

  const list = groups
    .map((group) => {
      const items = group.links
        .map((link) => {
          const [target = '', fragment] = link.target.split('#')
          // Current only for the page-level entry, with no fragment: a fragment link is one of
          // several sections of another page's entry, and marking every one of them current at
          // once (because they all resolve to this page) would be as good as marking none of them.
          const current =
            target === page.output && fragment === undefined ? ' aria-current="page"' : ''
          const detail =
            link.detail === undefined
              ? ''
              : `<span class="sidebar-detail">${escapeText(link.detail)}</span>`

          return `<li><a href="${escapeAttribute(`${href(target)}${fragment === undefined ? '' : `#${fragment}`}`)}"${current}>${escapeText(link.label)}${detail}</a></li>`
        })
        .join('\n          ')

      return `<div class="sidebar-group">
          <p class="sidebar-heading">${escapeText(group.heading)}</p>
          <ul>
          ${items}
          </ul>
        </div>`
    })
    .join('\n        ')

  return `<nav class="docs-sidebar" aria-label="Documentation">
        ${list}
      </nav>`
}

/**
 * The reading order docs pages keep a prev/next pair for: exactly the sidebar's "Start here" plus
 * "Set up, in order" flattened into one sequence, because that is the path somebody actually follows
 * start to finish. A page outside it (a spec, the plan, the reference) has no pair: nothing implies an
 * order across those the way the guide states one for itself.
 */
function readingOrder(
  context: BuildContext,
  steps: readonly SetupStep[],
): readonly { label: string; target: string }[] {
  const page = (source: string) => {
    const output = context.outputs.get(source)
    if (output === undefined) throw new Error(`the reading order cannot include ${source}`)

    return output
  }
  const setup = page('docs/setup.md')

  return [
    { label: 'What Caroline is', target: page('site/pages/index.md') },
    { label: 'Setting Caroline up', target: setup },
    ...steps.map((step) => ({
      label: `${step.number}. ${step.label}`,
      target: `${setup}#${step.anchor}`,
    })),
    { label: 'Using Caroline', target: page('docs/using.md') },
    { label: 'What leaves the machine', target: page('docs/content-policy.md') },
  ]
}

function prevNext(page: SitePage, context: BuildContext, steps: readonly SetupStep[]): string {
  const order = readingOrder(context, steps)
  const index = order.findIndex(
    (entry) => entry.target === page.output || entry.target.startsWith(`${page.output}#`),
  )
  if (index === -1) return ''

  const href = (target: string) => posix.relative(posix.dirname(page.output), target)
  const prev = index > 0 ? order[index - 1] : undefined
  const next = index < order.length - 1 ? order[index + 1] : undefined
  if (prev === undefined && next === undefined) return ''

  return `<nav class="prev-next" aria-label="Previous and next">
        ${prev === undefined ? '<span></span>' : `<a href="${escapeAttribute(href(prev.target))}" rel="prev">← ${escapeText(prev.label)}</a>`}
        ${next === undefined ? '<span></span>' : `<a href="${escapeAttribute(href(next.target))}" rel="next">${escapeText(next.label)} →</a>`}
      </nav>`
}

/**
 * The keys `using.md` and `setup.md` name inline, as `<kbd>` chips rather than the generic `<code>`
 * every other inline span gets. A fixed set rather than "every inline code span on this page", because
 * that would just as happily chip an environment variable or a config path: both pages carry those
 * too, and a chip is a claim about what a reader presses.
 */
const keyTokens = new Set([
  '←',
  '→',
  '↑',
  '↓',
  'h',
  'j',
  'k',
  'l',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  'd',
  'r',
  'a',
  'u',
  'c',
  'enter',
  'escape',
  'tab',
])

function chipKeys(html: string): string {
  return html.replace(/<code>([^<]+)<\/code>/g, (whole, inner: string) =>
    keyTokens.has(inner) ? `<kbd>${inner}</kbd>` : whole,
  )
}

/**
 * A "**Check it:**" paragraph, as a blue-tinted callout instead of a bold run of text at the start of
 * a paragraph. Matched on the rendered HTML rather than the Markdown, because by the time this runs
 * the bold span is already `<strong>Check it:</strong>`, and matching there is simpler than teaching
 * the renderer a new block type for one bold phrase.
 */
function calloutise(html: string): string {
  return html.replace(
    /<p><strong>Check it:<\/strong>\s*([\s\S]*?)<\/p>/g,
    (_whole, rest: string) =>
      `<div class="callout"><p class="callout-title">Check it</p><p>${rest}</p></div>`,
  )
}

interface Rendered {
  readonly html: string
  /** The `h2`s, in order: the table of contents of a long document. */
  readonly sections: readonly { readonly id: string; readonly label: string }[]
}

function render(markdown: string, page: SitePage, context: BuildContext): Rendered {
  const identifiers = new Set<string>()
  const sections: { id: string; label: string }[] = []
  const marked = new Marked({ gfm: true })
  /**
   * Collected here and thrown after the parse rather than from inside a renderer: `marked` catches what
   * a renderer throws and re-throws it with "Please report this to https://github.com/markedjs/marked."
   * appended, and the expected failure of this build is a broken link in somebody's pull request. Being
   * told to file a bug against a Markdown library is a poor answer to a typo. Collecting also reports
   * every bad link in a document rather than the first.
   */
  const failures: string[] = []

  marked.use({
    renderer: {
      heading(token: Tokens.Heading) {
        const label = this.parser.parseInline(token.tokens)
        const heading = slug(readAsText(label))
        // A heading of punctuation alone slugs to nothing, which would be `id=""` and a contents entry
        // pointing at `#`: a fragment that lands at the top of the page, past the check that a fragment
        // names a heading, because there is no fragment left to check.
        if (heading === '') {
          failures.push(
            `${page.source} has a heading with no identifier: "${token.text}" is punctuation, and a fragment cannot name it`,
          )
        }
        if (heading === contentIdentifier) {
          failures.push(
            `${page.source} has a heading whose identifier is "${contentIdentifier}", which is the one the page shell uses for its skip link: rename the heading`,
          )
        }
        let id = heading
        // Two headings can say the same thing. GitHub numbers the repeats, and so does this.
        for (let repeat = 1; identifiers.has(id); repeat += 1) id = `${heading}-${repeat}`
        identifiers.add(id)
        if (token.depth === 2) sections.push({ id, label })

        return `<h${token.depth} id="${escapeAttribute(id)}">${label}</h${token.depth}>\n`
      },

      /**
       * A screenshot from `docs/images`, and nothing else: the site copies that directory and no other,
       * so an image from anywhere would render as a request for a file that is not there. Refusing says
       * where the file belongs rather than leaving a reader's first visit to find out.
       *
       * The fragment carries the palette. `#gh-light-mode-only` and `#gh-dark-mode-only` are GitHub's
       * convention, already honoured wherever these documents are read there, so they are the spelling
       * rather than a second one invented here: the site turns each into the class its stylesheet hides
       * under the other theme. A fragment means nothing to an image otherwise, so any other is refused.
       */
      image(token: Tokens.Image) {
        const [path = '', ...rest] = token.href.split('#')
        const fragment = rest.join('#')
        const target = posix.normalize(posix.join(posix.dirname(page.source), path))
        const output = context.assets.get(target)

        if (output === undefined) {
          failures.push(
            `${page.source} embeds ${token.href}, which is no published image: the site copies ${imageDirectory} and nothing else`,
          )

          return ''
        }

        const palette = palettes[fragment]
        if (fragment !== '' && palette === undefined) {
          failures.push(
            `${page.source} embeds ${token.href}, and ${fragment} is not a palette: use ${Object.keys(palettes).join(' or ')}`,
          )
        }

        const source = posix.relative(posix.dirname(page.output), output)

        return `<img class="shot${palette === undefined ? '' : ` ${palette}`}" src="${escapeUrl(source)}" alt="${escapeAttribute(token.text)}" />`
      },

      link(token: Tokens.Link) {
        const href = resolve(token.href, page, context, failures)
        const title = token.title == null ? '' : ` title="${escapeAttribute(token.title)}"`
        const external = isAbsolute(href) ? ' rel="noopener" target="_blank"' : ''

        return `<a href="${escapeUrl(href)}"${title}${external}>${this.parser.parseInline(token.tokens)}</a>`
      },
    },
  })

  // The troubleshooting table is wider than a phone, and a table cell holds links of its own, so the
  // scroll box is wrapped round the rendered table rather than round a second rendering of it.
  let html = marked
    .parse(markdown, { async: false })
    // Any opening tag, not the bare one this renderer produces: a raw-HTML table with attributes would
    // otherwise take the page sideways on a phone and collect a closing `</div>` it never opened.
    .replace(/<table\b[^>]*>/g, (tag) => `<div class="table-scroll">${tag}`)
    .replaceAll('</table>', '</table></div>')

  html = calloutise(html)
  // The setup guide's own keyboard mentions ("Press `c` anywhere") and using.md's keyboard table and
  // reference row both name keys, so both pages get the chip treatment; nowhere else does, so a config
  // path or an environment variable elsewhere keeps its plain `<code>`.
  if (page.source === 'docs/using.md' || page.source === 'docs/setup.md') html = chipKeys(html)

  if (failures.length > 0) throw new Error(failures.join('\n'))

  return { html, sections }
}

/**
 * A link, from the file that holds it to the page that renders its target. Two answers: a page of the
 * site, or a defect.
 *
 * There is deliberately no third answer. This asked the filesystem whether an unpublished target
 * existed and linked it at the repository if it did, which made the build's verdict depend on the
 * machine it ran on: a path ignored by git resolved locally and 404'd on GitHub, and the same tree in
 * CI failed instead. No document links to a file rather than a document, so the fallback was answering
 * a question nobody asked, in a way that broke the one guarantee the build makes about itself. A
 * document that wants to point at a source file can write its URL.
 */
function resolve(href: string, page: SitePage, context: BuildContext, failures: string[]): string {
  // `[the guide]()` and `[the guide](#)` are typos that publish a link which reloads the page. A
  // fragment with something after the hash is a link within the page and resolves like any other.
  if (href === '' || href === '#') {
    failures.push(`${page.source} has a link with nothing to link to, written as "${href}"`)

    return href
  }
  if (isAbsolute(href) || href.startsWith('#')) return href

  const [path = '', ...rest] = href.split('#')
  const fragment = rest.length === 0 ? '' : `#${rest.join('#')}`
  if (path === '') return href

  const target = posix.normalize(posix.join(posix.dirname(page.source), path))
  const output = context.outputs.get(target)
  if (output !== undefined) {
    return `${posix.relative(posix.dirname(page.output), output)}${fragment}`
  }

  failures.push(
    `${page.source} links to ${href}, which is no page of this site: publish it, or write the URL of the file`,
  )

  // The href it was written with, so the rest of the page renders and every bad link in a document is
  // reported at once. Nothing is published: the failure is thrown before this page is laid out.
  return href
}

interface BuildContext {
  readonly sources: SiteSources
  /** Repository path to site path, which is what makes a link between two documents a link. */
  readonly outputs: ReadonlyMap<string, string>
  /** The same, for the images: repository path to the path they are copied to. */
  readonly assets: ReadonlyMap<string, string>
  readonly repository: string
}

/**
 * The palette a screenshot belongs to, by the fragment GitHub already reads it from, and the class the
 * site's stylesheet hides it under the other theme with. An image with no fragment is shown in both.
 */
const palettes: Readonly<Record<string, string>> = {
  'gh-light-mode-only': 'light-only',
  'gh-dark-mode-only': 'dark-only',
}

/**
 * The site's own prose, and the only page not rendered from a document: what Caroline is, whether
 * you want it, and where to start. `{{headline}}` and `{{subhead}}` are the README's own opening
 * paragraph, split at its first sentence, so the answer to "what is this" is written once and not
 * paraphrased for a headline; `{{start}}`, `{{requirements}}` and `{{afternoon}}` are built from
 * `site/pages/index.md`'s and `docs/setup.md`'s own words below.
 *
 * The hero's ASCII diagram from before this issue is gone rather than moved to spec 00: spec 00
 * already draws the system's architecture, in more useful detail than three boxes and an arrow, so a
 * second, shallower version of the same picture here would be the drift spec 11 exists to rule out.
 * The screenshot under the hero does the "does this actually work" job the diagram used to instead.
 */

/**
 * The README's opening paragraph: what Caroline is, written once. The home page renders it, and its
 * description is taken from it rather than from the page it is spliced into, because by then it is
 * rendered HTML and a description is prose.
 */
function readmeLede(sources: SiteSources): string {
  const lede = (paragraphs(sources.read('README.md'))[1] ?? '').trim()
  if (lede === '') {
    throw new Error('the README has no opening paragraph for the home page to render')
  }

  return lede
}

/**
 * The lede, split after its first sentence: the product claim as the headline, the rest as the
 * subhead the issue calls "the existing tagline". Split on the source Markdown rather than on
 * rendered HTML, so a link inside either half is still resolved by `render` rather than cut through.
 * A lede with no ". " at all (the suite's own override, testing link resolution) reads whole into the
 * headline and leaves the subhead empty, which still renders every word of it somewhere on the page.
 */
function splitLede(lede: string): { readonly headline: string; readonly subhead: string } {
  const boundary = lede.indexOf('. ')

  return boundary === -1
    ? { headline: lede, subhead: '' }
    : { headline: lede.slice(0, boundary + 1), subhead: lede.slice(boundary + 2) }
}

/**
 * A single paragraph of Markdown, rendered inline: links resolved exactly as `render` resolves them,
 * but without the `<p>` block it wraps prose in, so the caller can wrap the fragment in its own tag
 * and class. Safe for a fragment known to be one paragraph of running prose, which every hero fragment
 * here is.
 */
function renderInline(text: string, source: string, output: string, context: BuildContext): string {
  const html = render(text, { source, output, title: '' }, context).html

  return html.replace(/^<p>/, '').replace(/<\/p>\s*$/, '')
}

function homePage(page: SitePage, markdown: string, context: BuildContext): string {
  const lede = readmeLede(context.sources)
  const { headline, subhead } = splitLede(lede)
  const readme = (text: string) => renderInline(text, 'README.md', page.output, context)
  const steps = setupSteps(context.sources.read('docs/setup.md'))

  return markdown
    .replace('{{eyebrow}}', () => '<p class="hero-eyebrow">Self-hosted · single user · MIT</p>')
    .replace('{{headline}}', () => `<p class="hero-headline">${readme(headline)}</p>`)
    .replace('{{subhead}}', () =>
      subhead === '' ? '' : `<p class="hero-subhead">${readme(subhead)}</p>`,
    )
    .replace('{{requirements}}', () => `<p class="hero-requirements">${requirements(context)}</p>`)
    .replace('{{start}}', () => actions(context))
    .replace('{{shot}}', () => heroShot(context))
    .replace('{{refusals}}', () => `<p class="refusals-framing">${refusalsFraming(context)}</p>`)
    .replace('{{afternoon}}', () => afternoonSection(steps))
    .replace('{{footer}}', () => landingFooter(context))
}

/**
 * The landing page's own footer, inside the article rather than the site-wide one below it: the
 * licence line the site-wide footer already carries on every page, and links to the documents this
 * page's sections already point at, gathered in one place the way the mockup draws them.
 */
function landingFooter(context: BuildContext): string {
  const link = (source: string, label: string) => {
    const output = context.outputs.get(source)
    if (output === undefined) throw new Error(`the home page's footer cannot link to ${source}`)

    return `<a href="${output}">${label}</a>`
  }

  return `<div class="landing-footer">
  <p>Caroline is MIT-licensed, single-user, and runs on your own machine.</p>
  <p class="landing-footer-links">
    ${link('docs/specs/README.md', 'Documentation')}
    ${link('docs/content-policy.md', 'What leaves the machine')}
    <a href="${escapeAttribute(context.repository)}" rel="noopener" target="_blank">Source</a>
  </p>
</div>`
}

/**
 * One line of requirements, echoing `docs/setup.md`'s own opening claim: nothing here needs a
 * compiler, a container or a server, and Caroline is a usable manual GTD board before any
 * credentials are configured.
 */
function requirements(context: BuildContext): string {
  return renderInline(
    'Node 24, a browser, nothing to compile. A manual GTD board before you hand it any credentials.',
    'site/pages/index.md',
    'index.html',
    context,
  )
}

/**
 * The two things to do next, at the top rather than at the foot: a reader who has decided is not
 * going to scroll to find out where to go. The pages are looked up in the manifest rather than named
 * here, and the home page is at the site root, so a page's output path is already its href.
 *
 * The second link used to be "Read the documentation" pointed at `docs.html`; with that page gone it
 * points at the specs index instead, which is what `site/pages/index.md`'s own "Where to start"
 * paragraph already called "the documentation": "the specs are the contract each part is held to".
 */
function actions(context: BuildContext): string {
  const link = (source: string, label: string, attributes = '') => {
    const output = context.outputs.get(source)
    if (output === undefined) throw new Error(`the home page cannot link to ${source}`)

    return `<a${attributes} href="${output}">${label}</a>`
  }

  return `<p class="actions">
  ${link('docs/setup.md', 'Set it up', ' class="primary"')}
  ${link('docs/specs/README.md', 'Read the documentation')}
</p>`
}

/**
 * The screenshot under the hero: the dashboard, in both palettes, exactly as `using.md`'s "A worked
 * day" section already shows it. Reusing it rather than shooting a new one keeps criterion 12 true
 * with no change to `tools/demo`: the image is already named in `shoot.mjs`'s shot list, already
 * exists in both palettes, and is already shown by a document.
 */
function heroShot(context: BuildContext): string {
  const shot = (name: string, palette: string) => {
    const source = `docs/images/${name}.png`
    const output = context.assets.get(source)
    if (output === undefined) throw new Error(`the home page cannot show ${source}`)

    return `<img class="shot hero-shot ${palette}-only" src="${output}" alt="Caroline's dashboard: today's plan, the calendar, and the state of the machine" />`
  }

  return `<div class="hero-shot-frame">
    ${shot('dashboard', 'light')}
    ${shot('dashboard-dark', 'dark')}
  </div>`
}

/**
 * The framing above the four refusals: kept to two sentences already written elsewhere in this
 * repository's own copy rather than a new one composed for the mockup. The first is the README's
 * "Nothing is written back ... ever."; the second is `site/pages/index.md`'s own "Where to start"
 * sentence about the content policy, which already links it. The "enforcement rather than an
 * instruction" wording the issue asks to keep stays exactly where it already was, in the first bullet
 * below.
 */
function refusalsFraming(context: BuildContext): string {
  return renderInline(
    'Nothing is written back to GitHub, Gmail or Calendar, ever. ' +
      '[What leaves the machine](../../docs/content-policy.md) is worth reading before you point it ' +
      'at a work mailbox rather than after.',
    'site/pages/index.md',
    'index.html',
    context,
  )
}

/**
 * "Running in an afternoon, checked at every step": four cards built from `docs/setup.md`'s own step
 * table via `afternoonCards`, so the minutes here cannot say something the guide does not. The
 * footnote is `site/pages/index.md`'s own sentence, unchanged, about the two steps that cost people
 * an afternoon.
 */
function afternoonSection(steps: readonly SetupStep[]): string {
  const cards = afternoonCards(steps)
    .map(
      (card) => `<div class="afternoon-card">
      <p class="afternoon-time">${escapeText(card.time)}</p>
      <p class="afternoon-title">${escapeText(card.title)}</p>
      <p class="afternoon-body">${escapeText(card.body)}</p>
    </div>`,
    )
    .join('\n    ')

  return `<p class="afternoon-lede">Every integration is optional, one at a time and in any order.</p>
  <div class="afternoon-cards">
    ${cards}
  </div>
  <p class="afternoon-note">The two steps that cost people an afternoon, GitHub's token scopes and
  Google's consent screen, are called out where you meet them.</p>`
}

/** The first paragraph, as plain text: what a search result or a shared link shows. */
function description(markdown: string): string {
  // A paragraph, which is to say prose: not a heading, a table, a list, a quotation or a command. A
  // description built from a document's opening code fence is a line of shell in a search result.
  const prose = /^(#|>|\||[-*]\s|\d+\.\s|```| {4}|<)/
  const paragraph = paragraphs(markdown)
    .map((block) => block.trim())
    .find((block) => block !== '' && !prose.test(block))
  const sentence = (paragraph ?? '')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    // A description is plain text. Markup a document opens its first paragraph with would otherwise
    // arrive here as an escaped tag, which is neither a description nor anything a reader wants.
    .replace(/<[^>]*>/g, '')
    .replace(/[`*_]/g, '')
    .replace(/\s+/g, ' ')
    .trim()

  if (sentence.length <= 160) return sentence

  // A whole sentence where the paragraph offers one within the length, and a whole word otherwise.
  // Cutting mid-word is how a description ends up reading as a truncated database column.
  const stop = sentence.slice(0, 161).lastIndexOf('. ')
  if (stop >= 60) return sentence.slice(0, stop + 1)

  // A paragraph whose first 158 characters hold no space has no word boundary to cut at, and
  // `lastIndexOf` returning -1 through `slice` would drop one character rather than truncate.
  const boundary = sentence.lastIndexOf(' ', 157)

  return `${sentence.slice(0, boundary === -1 ? 157 : boundary)}…`
}

function layout(
  page: SitePage,
  rendered: Rendered,
  markdown: string,
  context: BuildContext,
): string {
  // Every reference on the page, asset or page, is relative to this page: a project site is served
  // under a path, and a root-relative link is one that works on the machine it was built on.
  const href = (output: string) => posix.relative(posix.dirname(page.output), output)
  const links = navigation
    .map((entry) => {
      const current = entry.output === page.output ? ' aria-current="page"' : ''
      return `<a href="${escapeAttribute(href(entry.output))}"${current}>${entry.label}</a>`
    })
    .join('\n        ')
  const contents =
    rendered.sections.length < 3 || page.output === 'index.html'
      ? ''
      : `<nav class="toc" aria-label="On this page">
        <p class="toc-label">On this page</p>
        <ol>
          ${rendered.sections
            .map(
              // The label is text and not the heading's rendered HTML: a heading carrying a link would
              // otherwise put an anchor inside this one, which a browser closes early, and half the
              // entry stops linking to the fragment while the rest leaves the page.
              (section) =>
                `<li><a href="#${escapeAttribute(section.id)}">${escapeText(readAsText(section.label))}</a></li>`,
            )
            .join('\n          ')}
        </ol>
      </nav>`
  const title = page.output === 'index.html' ? 'Caroline' : `${page.title} · Caroline`

  // Every page but the home page gets the docs shell's grouped sidebar: it is what replaced the flat
  // top nav's job of getting a reader from one document to another, so it belongs on every document
  // and not only the ones the mockups happened to show.
  const steps = setupSteps(context.sources.read('docs/setup.md'))
  const shell = page.output === 'index.html' ? '' : sidebar(page, context, steps)
  const foot = page.output === 'index.html' ? '' : prevNext(page, context, steps)
  const mainClasses = [
    page.output === 'index.html' ? 'home' : 'document',
    contents === '' ? '' : 'with-contents',
    shell === '' ? '' : 'with-sidebar',
  ]
    .filter((name) => name !== '')
    .join(' ')

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeText(title)}</title>
    <meta name="description" content="${escapeAttribute(description(markdown))}" />
    <link rel="icon" href="${href('icon.svg')}" type="image/svg+xml" />
    <link rel="stylesheet" href="${href('styles.css')}" />
  </head>
  <body>
    <a class="skip" href="#content">Skip to the content</a>
    <header class="site-header">
      <a class="wordmark" href="${escapeAttribute(href('index.html'))}">Caroline</a>
      <nav class="site-nav" aria-label="Site">
        ${links}
        <a href="${escapeAttribute(context.repository)}" rel="noopener" target="_blank">Source</a>
      </nav>
    </header>
    <main id="${contentIdentifier}" tabindex="-1" class="${mainClasses}">
      ${shell}
      ${contents}
      <div class="doc-column">
        <article>
${rendered.html.trimEnd()}
        </article>
        ${foot}
      </div>
    </main>
    <footer class="site-footer">
      <p>
        This page is
        <a href="${escapeAttribute(`${context.repository}/blob/main/${page.source}`)}" rel="noopener" target="_blank"><code>${escapeText(page.source)}</code></a>
        in the repository, rendered. Corrections belong to the file rather than to the site.
      </p>
      ${
        // The home page's own footer, inside the article, already carries this line: repeating it
        // here would print it twice on the one page that has it. Every other page carries it once,
        // here.
        page.output === 'index.html'
          ? ''
          : '<p>Caroline is MIT-licensed, single-user, and runs on your own machine.</p>'
      }
    </footer>
  </body>
</html>
`
}

/**
 * The stylesheet with its comments blanked out, character for character, so that every index into it is
 * still an index into the original. Prose about a rule is not a rule: `:root {` in a sentence would
 * otherwise be where the palette is read from, and the first `--accent:` in a comment would be the
 * colour of the favicon.
 */
const withoutComments = (css: string): string =>
  css.replace(/\/\*[\s\S]*?\*\//g, (comment) => ' '.repeat(comment.length))

/**
 * The application's palette, lifted whole. Spec 10 owns these values; the site is a second set of
 * rules over the same tokens, and extracting the blocks is what stops it becoming a second palette.
 */
function palette(application: string): string {
  const blocks = [':root {', '@media (prefers-color-scheme: light) {']
    .map((opening) => block(application, opening))
    .join('\n\n')

  return `/*
 * Extracted from web/styles.css by site/build.ts. Spec 10 decides these values, and the site and the
 * application share them so that they read as one piece of work. Edit them there.
 */
${blocks}
`
}

/**
 * The seven tokens the hero pins itself to regardless of `prefers-color-scheme`: the page, the two
 * ink tones, the raised surface, the hairline, and the one filled primary. Named here once, so
 * `heroPin` and the values it emits cannot drift apart from each other, let alone from the
 * application.
 */
const heroTokens = [
  'page',
  'ink',
  'ink-quiet',
  'surface-raised',
  'line',
  'primary',
  'primary-ink',
] as const

/**
 * The hero's pin to the application's dark palette, read by name from `web/styles.css`'s own
 * `:root` block rather than retyped: `:root` is unconditioned dark (issue #47), so these are
 * already the values a system with no light preference gets, and reading them here is what keeps
 * the hero's "always dark" rule from silently drifting the moment that palette moves without this
 * file moving with it. Same mechanism `icon` already uses to read `--accent`/`--primary-ink` by
 * name, applied to the seven tokens `.hero` overrides.
 */
function heroPin(application: string): string {
  const dark = withoutComments(block(application, ':root {'))
  const token = (name: string) => new RegExp(`--${name}:\\s*([^;]+);`).exec(dark)?.[1]?.trim()

  const declarations = heroTokens
    .map((name) => {
      const value = token(name)
      if (value === undefined) {
        throw new Error(`web/styles.css declares no --${name} for the hero to pin`)
      }

      return `  --${name}: ${value};`
    })
    .join('\n')

  return `/*
 * The hero's pin to the application's dark palette. Extracted from web/styles.css's own :root
 * block by site/build.ts, the same way palette() and icon() read theirs, so these values cannot
 * drift from the ones they name. Edit the palette in web/styles.css, not the values here.
 */
.hero {
${declarations}
}
`
}

/**
 * From an opening brace to the one that closes it, counting the pairs between.
 *
 * Read from the blanked copy so that neither the opening nor a brace can be found inside a comment, and
 * sliced from the original so that the palette keeps the comments it is written with. The opening is
 * matched only at the top level, so `:root {` means the palette and not the `:root {` inside the dark
 * media query: taking the first occurrence made the answer depend on which palette was written first,
 * which is a stylesheet somebody may reorder for reasons of their own.
 */
function block(css: string, opening: string): string {
  const searchable = withoutComments(css)
  let depth = 0
  let start = -1

  for (let index = 0; index < searchable.length; index += 1) {
    if (start === -1 && depth === 0 && searchable.startsWith(opening, index)) {
      start = index
      index += opening.length - 1
      depth = 1
      continue
    }
    if (searchable[index] === '{') depth += 1
    else if (searchable[index] === '}') {
      depth -= 1
      if (depth === 0 && start !== -1) return css.slice(start, index + 1)
    }
  }

  if (start === -1) throw new Error(`web/styles.css has no ${opening} block for the site to share`)

  throw new Error(`web/styles.css leaves ${opening} unclosed`)
}

/**
 * The favicon: a C in the application's accent, with both colours taken from the tokens rather than
 * chosen again here. It has one palette and not two, because a browser tab is drawn from a cached
 * image and knows nothing about the reader's theme, so it takes the light pair.
 *
 * Read from the light media query block rather than from the bare `:root` one: issue #47 made dark
 * the application's unconditioned default, so "the light pair" is now the override rather than the
 * block written first, and reading it by name rather than by position is what keeps this correct
 * regardless of which palette a future edit writes first.
 */
function icon(application: string): string {
  const light = withoutComments(block(application, '@media (prefers-color-scheme: light) {'))
  const token = (name: string) => new RegExp(`--${name}:\\s*([^;]+);`).exec(light)?.[1]?.trim()
  // `--primary-ink` rather than a dedicated "accent-ink": the redesign's one filled primary is
  // neutral, not chromatic, and this is the one place outside the application itself that still
  // wants a colour proven to read against a filled accent square.
  const [accent, ink] = [token('accent'), token('primary-ink')]
  if (accent === undefined || ink === undefined) {
    throw new Error('web/styles.css declares no accent/primary-ink pair for the icon')
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="7" fill="${accent}" />
  <path d="M22 21.5a9 9 0 1 1 0-11" fill="none" stroke="${ink}" stroke-width="3.5" stroke-linecap="round" />
</svg>
`
}

/**
 * What a page may link out over, and nothing else. `javascript:` and `data:` are the two that make a
 * link into code, and a documentation site has no use for either.
 *
 * `marked` does not sanitise, and this is deliberately not a sanitiser: the Markdown rendered here is
 * authored in this repository and reviewed as code, so an unsafe URL or a `<script>` in a document is
 * a mistake, and the build refusing to publish it is a better answer than quietly rewriting what
 * somebody wrote. Anyone who can commit a `javascript:` URL to `docs/` can commit to this file too.
 *
 * `mailto:` is not on the list, and that is the second criterion agreeing with the eighth rather than
 * an omission: no page of this site may carry an address, so a link that is one is a leak with a
 * scheme in front of it. The issues are the way to reach anybody.
 */
const schemes = ['http:', 'https:']

/**
 * A tag, quotes and all. `[^>]*>` ends a tag at the first `>`, which a quoted attribute value is
 * allowed to contain: `<a title=">" href="javascript:alert(1)">` would end at the title and the href
 * would never be read, which is precisely the tag somebody would write to get one past this.
 */
const tagPattern = /<[a-z][a-z0-9]*(?:"[^"]*"|'[^']*'|[^>"'])*>/gi

/**
 * The attributes that name something to fetch or somewhere to go. `data` is here because `<object>` uses
 * it, and a check that reads only `href` and `src` publishes `data="javascript:…"` untouched.
 */
const references = new Set(['href', 'src', 'data', 'srcset', 'poster'])

/**
 * The attributes of one tag, read left to right, so that what a value says cannot be taken for the name
 * of another attribute. Looking for `href=` anywhere in a tag finds it inside
 * `<meta content="… href=x …">`, where it is a document's prose rather than a link, and refuses to
 * publish a page over a sentence somebody wrote.
 */
function attributesOf(tag: string): [string, string][] {
  const interior = tag.replace(/^<[a-z][a-z0-9]*/i, '').replace(/\/?>$/, '')
  const pattern = /([a-z][a-z0-9-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/gi

  return [...interior.matchAll(pattern)].map((match) => [
    (match[1] ?? '').toLowerCase(),
    match[2] ?? match[3] ?? match[4] ?? '',
  ])
}

/**
 * Every page and every link, checked against what was built. The build refuses rather than publishing
 * a page that sends a reader nowhere, because the one thing this site exists to do is get somebody
 * from the front page to a running Caroline.
 */
function verify(files: ReadonlyMap<string, string>, assets: ReadonlySet<string>): void {
  const identifiers = (contents: string) =>
    new Set([...contents.matchAll(/id="([^"]*)"/g)].map((match) => match[1]))

  for (const [path, contents] of files) {
    if (!path.endsWith('.html')) continue

    // Criterion 7, enforced where it matters rather than only asserted: a script that reached a page
    // through a document's raw HTML would otherwise be published and noticed by the suite afterwards.
    // `<style>` is here because the site has one stylesheet and an inline one can `@import` from
    // anywhere; `<object>` and `<embed>` because they are an `<iframe>` by another name. An `<img>` is
    // not on the list any more, because the site publishes screenshots: what an image may point at is
    // checked below, exactly as a link is, and a raw one from another host still fails there.
    // Comments out first: a tag parked inside one is not a tag the page carries, and refusing to publish
    // a page over `<!-- <img src="x"> -->` would be a build failing on something a browser never reads.
    const published = contents.replace(/<!--[\s\S]*?-->/g, '')
    const forbidden = /<(script|iframe|object|embed|style)\b/i.exec(published)
    if (forbidden !== null) {
      throw new Error(`${path} carries ${forbidden[0]}, which a page of this site does not`)
    }

    // The tags, and the attributes inside them. Every form of an attribute, not the one this generator
    // writes, because a raw `<a HREF='javascript:…'>` in a document reaches the page untouched. Reading
    // the page rather than its tags would read escaped prose too, and a document that shows an anchor
    // in a code sample would fail the build on a link nobody wrote.
    for (const match of published.matchAll(tagPattern)) {
      const element = (/^<([a-z][a-z0-9]*)/i.exec(match[0])?.[1] ?? '').toLowerCase()

      for (const [name, value] of attributesOf(match[0])) {
        if (name.startsWith('on')) {
          throw new Error(`${path} sets ${name}, and a page of this site runs nothing`)
        }
        if (!references.has(name)) continue
        const href = value.replace(/&amp;/g, '&')
        // The raw-HTML spelling of the same typo: a reference to nothing, which reloads the page.
        if (href === '' || href === '#') {
          throw new Error(`${path} has a <${element}> with nothing to link to`)
        }

        if (isAbsolute(href)) {
          if (!schemes.some((scheme) => href.toLowerCase().startsWith(scheme))) {
            throw new Error(
              `${path} links to ${href}, over a scheme this site does not link out with`,
            )
          }
          // An anchor is a reader choosing to go somewhere. Anything else is the page fetching from
          // another host as it loads, which is the whole of what criterion 7 says it does not do: a
          // stylesheet, a font or an image from a CDN is also a record of who read the page.
          if (element !== 'a') {
            throw new Error(
              `${path} fetches ${href} in a <${element}>, and a page of this site fetches nothing from another host`,
            )
          }
          continue
        }

        // Root-relative, which normalises into something that resolves here and points at another site
        // once this one is served under a path. Criterion 5, and the one form of it that looked fine.
        if (href.startsWith('/')) {
          throw new Error(`${path} links to ${href}, which is root-relative rather than relative`)
        }

        // Split at the first `#` only. The rest is the fragment, `#` and all: a browser asks for the
        // whole of it, so validating the part before a second `#` would pass a link that lands nowhere.
        const separator = href.indexOf('#')
        const target = separator === -1 ? href : href.slice(0, separator)
        const fragment = separator === -1 ? '' : href.slice(separator + 1)
        const page = target === '' ? path : posix.normalize(posix.join(posix.dirname(path), target))

        // An image is copied rather than built, so it is in neither `files` nor a heading. A fragment on
        // one is a defect and not a palette: the renderer turns a palette into a class and writes the
        // reference without it, so anything left here would be asking a browser for part of a PNG.
        if (assets.has(page)) {
          if (fragment !== '') {
            throw new Error(`${path} references ${href}, and an image has no ${fragment} in it`)
          }
          continue
        }

        const rendered = files.get(page)
        if (rendered === undefined) {
          throw new Error(`${path} links to ${href}, which the build did not produce`)
        }
        if (fragment !== '' && !identifiers(rendered).has(fragment)) {
          throw new Error(`${path} links to ${href}, and ${page} has nothing called ${fragment}`)
        }
      }
    }
  }
}

/** The site, as a map of path to contents. Nothing is written here: `site/main.ts` does that. */
export function buildSite(sources: SiteSources = repositorySources()): Map<string, string> {
  const entries = manifest(sources)
  const assets = siteAssets(sources)
  const context: BuildContext = {
    sources,
    outputs: new Map(entries.map((entry) => [entry.source, entry.output])),
    assets: new Map(assets.map((asset) => [asset.source, asset.output])),
    repository: repositoryUrl(sources),
  }

  const files = new Map<string, string>()

  for (const entry of entries) {
    const home = entry.output === 'index.html'
    const markdown = home
      ? homePage(entry, sources.read(entry.source), context)
      : sources.read(entry.source)
    // The home page describes itself with the README's paragraph rather than with its own first block:
    // by the time the markers are filled that block is rendered HTML, and the first prose paragraph
    // after it is a section about Node versions. The description of the front page is the one that is
    // read most and seen least.
    const describing = home ? readmeLede(sources) : markdown
    files.set(entry.output, layout(entry, render(markdown, entry, context), describing, context))
  }

  const application = sources.read('web/styles.css')
  files.set(
    'styles.css',
    `${palette(application)}\n${heroPin(application)}\n${sources.read('site/styles.css')}`,
  )
  files.set('icon.svg', icon(application))

  verify(files, new Set(assets.map((asset) => asset.output)))

  return files
}
